### ISSUE TITLE
i can't run it

### ISSUE THREAD

**Issue by velicumugur** [JerryWm/Stratum-Proxy-XMR#5]
root@proxy:~/Stratum-Proxy-XMR/src# node ./app/
/root/Stratum-Proxy-XMR/src/app/main.js:28
        let config = null;
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
root@proxy:~/Stratum-Proxy-XMR/src#

**Comment by JerryWm** [comment]
Install the latest version of nodejs

**Comment by velicumugur** [comment]
i'm user vacarosie200 on bitcontalk , i just setu a new vps ,, it's latest nodejs ... ubuntu 16.04

**Comment by velicumugur** [comment]
root@proxy:~/Stratum-Proxy-XMR/src# apt install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.1).
nodejs set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
root@proxy:~/Stratum-Proxy-XMR/src# node
The program 'node' is currently not installed. You can install it by typing:
apt install nodejs-legacy
root@proxy:~/Stratum-Proxy-XMR/src# The program 'node' is currently not installed
No command 'The' found, did you mean:
 Command 'the' from package 'the' (universe)
The: command not found
root@proxy:~/Stratum-Proxy-XMR/src# nodejs ./app/
/root/Stratum-Proxy-XMR/src/app/main.js:28
        let config = null;
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
root@proxy:~/Stratum-Proxy-XMR/src#

**Comment by naufan385** [comment]
On raspberry pi ubuntu is work
Install latest nodejs(9.4.0). 
Thank you.
